const v1Router = require("express").Router();
const loginRouter = require("./loginRoutes");
const adminRouter = require("./adminRoutes");
const userRouter = require("./userRoutes");
const trainerRouter = require("./trainerRoutes");
const activityRouter = require("./ActivityRoutes");
const fitnessProgramRouter = require("./fitnessProgramRoutes");
const personalSessionRouter = require("./personalSessionRoutes");
const paymentRouter = require("./paymentRoutes");
const chatRouter = require("./chatRoutes");
v1Router.use("/auth", loginRouter);
v1Router.use("/user", userRouter);
v1Router.use("/admin", adminRouter);
v1Router.use("/trainer", trainerRouter);
v1Router.use("/fitness-program", fitnessProgramRouter);
v1Router.use("/activity", activityRouter);
v1Router.use("/personal-session", personalSessionRouter);
v1Router.use("/payment", paymentRouter);
v1Router.use("/chat", chatRouter);
module.exports = v1Router;
